---
- name: Merged Operation
  hosts: junos-lab
  collections:
    - junipernetworks.junos
  tasks:
    - name: "gather facts for junos layer 2 interfaces"
      junipernetworks.junos.junos_l2_interfaces:
        config:
        state: gathered