---
- name: Merged operation
  hosts: junos-lab
  collections:
    - junipernetworks.junos
  tasks:
    - name: Configure vlan
      junipernetworks.junos.junos_config:
        lines:
          - set vlans vlan100 vlan-id 100
          - set vlans vlan200 vlan-id 200
          - set vlans vlan300 vlan-id 300
          - set vlans vlan400 vlan-id 400
    - name: Merge the provided configuration with the exisiting running configuration
      register: result
      junipernetworks.junos.junos_l2_interfaces:
        config:

          - name: ge-0/0/1
            access:
              vlan: vlan100

          - name: ge-0/0/2
            trunk:
              allowed_vlans:
                - vlan200
                - vlan300
              native_vlan: '400'
        state: merged
