---
- name: Using Aggregate with task
  hosts: iosxr-local
  collections:
    - cisco.iosxr
  tasks:
    - name: remove logging parameters using aggregate
      cisco.iosxr.iosxr_logging:
        aggregate:

          - dest: console
            level: notifications

          - dest: buffered
            size: 4700000

          - dest: monitor
            level: alerts

          - dest: host
            name: 10.10.10.1
            level: errors

          - dest: host
            name: 10.10.10.2

          - dest: file
            name: file1
            size: 2048
            level: critical

          - dest: file
            name: file2
            size: 2048

          - facility: local3

          - hostnameprefix: host3
        state: absent
        provider: '{{ netconf }}'
    - name: Change logging parameters using aggregate
      register: result
      iosxr_logging:
        aggregate:

          - dest: console
            level: notifications

          - dest: buffered
            size: 4700000

          - dest: monitor
            level: alerts

          - dest: host
            name: 10.10.10.1
            level: errors

          - dest: host
            name: 10.10.10.2

          - dest: file
            name: file1
            size: 2048
            level: critical

          - dest: file
            name: file2
            size: 2048

          - facility: local3

          - hostnameprefix: host3
        state: present
        provider: '{{ netconf }}'

    - name: Print result
      debug:
        var: result
    - assert:
        that:
          - result.changed == true
          - '"file1" in result.xml[0]'
          - '"file2" in result.xml[0]'
          - '"10.10.10.1" in result.xml[1]'
          - '"10.10.10.2" in result.xml[1]'
          - '"notice" in result.xml[2]'
          - '"alert" in result.xml[3]'
          - '"4700000" in result.xml[4]'
          - '"debug" in result.xml[5]'
          - '"local3" in result.xml[6]'
          - '"host3" in result.xml[7]'
    - name: Print result
      debug:
        var: result.xml[5]