---
- name: Merged operation
  hosts: junos-rdo
  collections:
    - junipernetworks.junos
  tasks:
    - name: get supported protocols
      register: result
      ignore_errors: true
      junipernetworks.junos.junos_command:
        commands: show lldp

    - name: lldp supported
      set_fact:
        lldp_supported: true
      when: not result.failed

    - name: lldp not supported
      set_fact:
        lldp_supported: false
      when: result.failed
    - name: Merge the provided configuration with the exisiting running configuration
      register: result
      junipernetworks.junos.junos_lldp_global: &id001
        config:
          interval: 10000
          address: 10.1.1.1
          transmit_delay: 400
          hold_multiplier: 10
        state: merged
