---
- name: integration test for gathered
  hosts: junos-lab
  collections:
    - junipernetworks.junos
  tasks:
    - name: set facts
      set_fact:
        expected_merged_output:

          - name: ge-1/0/0
            ipv4:

              - address: 192.168.100.1/24

              - address: 10.200.16.20/24
            unit: "0"
          - name: ge-2/0/0
            ipv4:

              - address: 192.168.100.2/24

              - address: 10.200.16.21/24
            unit: "0"

          - name: ge-3/0/0
            ipv4:

              - address: 192.168.100.3/24

              - address: 10.200.16.22/20
            unit: "0"

    - block:

        - name: Merge the provided configuration with the exisiting running configuration
          register: result
          junipernetworks.junos.junos_l3_interfaces: &id001
            config:

              - name: ge-1/0/0
                ipv4:

                  - address: 192.168.100.1/24

                  - address: 10.200.16.20/24

              - name: ge-2/0/0
                ipv4:

                  - address: 192.168.100.2/24

                  - address: 10.200.16.21/24

              - name: ge-3/0/0
                ipv4:

                  - address: 192.168.100.3/24

                  - address: 10.200.16.22/24
            state: replaced

        - name: Gather l3_interfaces facts using gathered state
          register: result
          junipernetworks.junos.junos_l3_interfaces:
            state: gathered
        - name: Print result
          debug:
            var: result
        - assert:
            that:
              - result.gathered[0].name == 'ge-1/0/0'
              - result.gathered[0].ipv4[0]['address'] == '192.168.100.1/24'
              - result.gathered[0].ipv4[1]['address'] == '10.200.16.20/24'
              - result.gathered[1].name == 'ge-2/0/0'
              - result.gathered[1].ipv4[0]['address'] == '192.168.100.2/24'
              - result.gathered[1].ipv4[1]['address'] == '10.200.16.21/24'
              - result.gathered[2].name == 'ge-3/0/0'
              - result.gathered[2].ipv4[0]['address'] == '192.168.100.3/24'
              - result.gathered[2].ipv4[1]['address'] == '10.200.16.22/24'


#        - name: Assert that facts were correctly generated
#          assert:
#            that: "{{ expected_merged_output | symmetric_difference(result['gathered']) |length\
#              \ == 0 }}"




