---
- name: Parsed Playbook For Junos L2-interfaces
  hosts: junos-lab
  collections:
    - cisco.iosxr
  tasks:
    - name: Parsed the runing-config
      junipernetworks.junos.junos_l3_interfaces:
        running_config: "{{lookup('file', './netconf_data/parsed.cfg')}}"
        state: parsed