---
- name: Merged Operation
  hosts: junos-rdo
  collections:
    - junipernetworks.junos
  tasks:
    - name: "gather facts for junos interfaces"
      junipernetworks.junos.junos_ospfv2:
        state: gathered