---
- name: Render operation
  hosts: junos-lab
  collections:
    - junipernetworks.junos
  tasks:
    - name: Render xml tree for provided config
      junipernetworks.junos.junos_lag_interfaces: &id001
        config:
          - name: ae1
            members:
              - member: ge-0/0/1
              - member: ge-0/0/2
            mode: active

          - name: ae2
            link_protection: true
            members:
              - member: ge-0/0/3
                link_type: primary
              - member: ge-0/0/4
                link_type: backup
            mode: passive
        state: rendered