---
- name: Merged Operation
  hosts: junos-lab
  collections:
    - junipernetworks.junos
  tasks:
    - name: "gather facts for junos interfaces"
      junipernetworks.junos.junos_lldp_interfaces:
        state: gathered