---
- name: Deleted  operation
  hosts: junos-rdo
  collections:
    - junipernetworks.junos
  tasks:
    - name: Delete an area
      junipernetworks.junos.junos_ospfv3:
        config:
          - router_id: 10.200.16.75
            areas:
              - area_id: 0.0.0.100
                interfaces:
                  - name: so-0/0/0.0
        state: deleted
#    - name: Merge the provided configuration with the exisiting running configuration
#        register: result
#        junipernetworks.junos.junos_ospfv3: &id001
#          config:
#            - router_id: 10.200.16.75
#              areas:
#                - area_id: 0.0.0.100
#                  stub:
#                    default_metric: 200
#                    set: true
#                  interfaces:
#                    - name: so-0/0/0.0
#                      priority: 3
#                      metric: 5
#          state: merged
