---
- name: Parsed Playbook For Junos interfaces
  hosts: junos-rdo
  collections:
    - junipernetworks.junos
  tasks:
    - name: Parsed the runing-config
      junipernetworks.junos.junos_ospfv3:
        running_config: "{{lookup('file', './netconf_data/parsed.cfg')}}"
        state: parsed