---
- name: Merged operation
  hosts: junos-rdo
  collections:
    - junipernetworks.junos
  tasks:

    - name: Replace configuration
      junos_ospfv3:
        config:
          - router_id: 10.200.16.75
            areas:
              - area_id: 0.0.0.100
                interfaces:
                  - name: so-0/0/0.0
        state: replaced