---
- name: Render operation
  hosts: junos-lab
  collections:
    - junipernetworks.junos
  tasks:
    - name: Render xml tree for provided config
      junipernetworks.junos.junos_lacp_interfaces: &id001
        config:
          - name: ae1
            period: fast
            sync_reset: enable
            system:
              priority: 100
              mac:
                address: 00:00:00:00:00:02

          - name: ge-0/0/1
            port_priority: 100
            force_up: true
        state: rendered